openapi: 3.0.3
info:
  title: Browser RTS Game
  description: A learning experience creating a time based game
  version: 1.0.0
servers:
- url: /api/v1

tags:
  - name: authentication
    description: Authentication related operations
 
paths:
  /register:
    post:
      summary: Registers a new user
      tags: 
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
  /login:
    post:
      summary: Authenticates a user
      tags: 
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
  /user:
    get:
      summary: Retrieves information about the authenticated user
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        401:
          description: Unauthenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponse'
 
components:
  schemas:
    RegisterUserRequest:
      type: object
      additionalProperties: false
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    LoginUserRequest:
      type: object
      additionalProperties: false
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
    AuthenticationResponse:
      type: object
      properties:
        accessToken: 
          type: string
        refreshToken: 
          type: string
        expiresIn: 
          type: integer
    UserResponse:
      type: object
      properties:
        email: 
          type: string
    UnauthorizedErrorResponse:
      type: object
      properties:
        error: 
          type: object
          properties:
            type:
              type: string
            message:
              type: string
            errors:
              type: array